// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
// This file contains the Supabase client configuration and initialization
// Example Supabase URL and Anon Key
// Replace these with your actual Supabase project details
const SUPABASE_URL = "https://your_supabase_id.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "your_anon_key";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});